// // prettier.config.js
// module.exports = {
//   bracketSpacing: true,
//   semi: true,
//   trailingComma: "all",
//   printWidth: 80,
//   tabWidth: 2,
//   importOrder: [
//     "^(react/(.*)$)|^(react$)",
//     "^(next/(.*)$)|^(next$)",
//     "^types$",
//     "^@/types/(.*)$",
//     "^@/config/(.*)$",
//     "^@/lib/(.*)$",
//     "^@/hooks/(.*)$",
//     "^@/components/*/(.*)$",
//     "^@/components/(.*)$",
//     "^@/registry/(.*)$",
//     "^@/styles/(.*)$",
//     "^@/app/(.*)$",
//     "",
//     "^[./]",
//   ],
//   importOrderSeparation: false,
//   importOrderSortSpecifiers: true,
//   importOrderBuiltinModulesToTop: true,
//   importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
//   importOrderMergeDuplicateImports: true,
//   importOrderCombineTypeAndValueImports: true,
//   plugins: [require("prettier-plugin-tailwindcss"), "@ianvs/prettier-plugin-sort-imports"],
// };
