export const mandatoryColumns = [
  "Channel",
  "Region",
  "CategoryName",
  "Family",
  "subFamily",
  "Supplier",
  "SubCategory",
  "ItemLookupCode",
  "Budget%",
  "OTBorPurchaseCost",
  "BudgetvsACT_FCT",
  "BudgetvsLY%",
  "BudgetvsLLY%",
  "BudgetQTY",
  "Logistic%",
  "ProposedSellThru%",
  "DisplayItem",
  "COR_valueENDOfLifeStock",
  "RelativeBudget%",
  "Budget%",
  "Budget vs Act/Forecast %",
  "Budget vs PY%",
  "Budget vs PPY%",
  "Units Buy By SKU",
  "Units/SKU",
  "Budget/SKU",
];
