export const nonDefaultColumns = {
  // Department_Name: false,
  // DOM_COMM: false,
  // ExtendedSubCategory: false,
  // SubCategorySupplier: false,
  // ENDOFLife: false,
  // Description: false,
  // BudgetYear: false,
  // HistoricalYear: false,
  // BudgetVSLY: false,
  // BudgetvsLLY: false,
  // AssemblyCodeNickname: false,
  // StoreName: false,
  // CategoryName: false,
  // Supplier: false,
  // SubCategory: false,
  // ItemLookupCode: false,
  // subFamily: false,
  // Status: false,
  // BugetVSLY: false,
  // StoreId: false,
  // "RelativeBudget%": false,
  // BudgetYear: false,
};
