const columns: any = {
  Channel: "Channel",
  Region: "Region",
  StoreId: "Store_Id",
  StoreName: "Store_Name",
  Department_Name: "Department_Name",
  CategoryName: "Category_Name",
  Family: "Family",
  subFamily: "Sub_Family",
  DOM_COMM: "DOM/COMM",
  Supplier: "Supplier",
  SubCategory: "Sub_Category",
  ExtendedSubCategory: "Extended_Sub_Category",
  SubCategorySupplier: "Sub_Category_Supplier",
  AssemblyCodeNickname: "Assembly_Code_Nickname",
  ItemLookupCode: "Item_Lookup_Code",
  Status: "Status",
  ENDOFLife: "End_Of_Life",
  Description: "Description",
  BudgetYear: "Budget_Year",
  HistoricalYear: "Historical_Year",
  BudgetAmount: "Budget_Amount",
  "Budget%": "Budget %",
  Net_Sales: "Net_Sales",
  BudgetvsACT_FCT: "Budget vs Act/FCT",
  "BudgetVSLY%": "Budget_vs_LY%",
  "BudgetvsLLY%": "Budget vs LLY%",
  Price: "Budget Price",
  BudgetQTY: "Budget_QTY",
  QTY_SKU: " Quanity/SKU",
  Budget_SKU: "Budget/SKU",
  Item_Cost: "Item_Cost",
  LY_Gross_Margin: "LY_Gross_Margin",
  BudgetCost: "Budget_Cost",
  "BudgetGrossMargin%": "Budget_Net_Margin%",
  BudgetCostofGoods: "Budget_Cost_Of_Goods",
  "Logistic%": "Logistic %",
  SupplyCost: "Supply_Cost",
  "FirstMargin%": "First_Margin%",
  StockQuantity: "Stock_Quantity",
  "LYsellThru%": "LY_Selthru%",
  "ProposedSellThru%": "Proposed_Selthru%",
  PurchasedRetailValueGrossSale: "Purchased_Retail_Value_Gross_Sale",
  StockatRetailPrice: "Stockat_Retail_Price",
  DisplayItem: "Display_Item",
  DisplayItemValue: "Display_Item_Value",
  COR_valueENDOfLifeStock: "COR_Value_On_End_Of_Life_Stock",
  TYForecast: "TY_Forecast  OP STOCK @ Retail Value",
  PurchaseReatilValueatGrossSale: "Purchased_Retail_Value_Gross_Sale",
  OTBorPurchaseCost: "OTB",
  "RelativeBudget%": "Relative_Budget%",
  SoldQuantity: "Sold_Quantity",
  PO: "Expected PO",
  Historical_Gross_Margin: "Historical_Net_Margin",
  "Adjusted_Gross_Margin%": "Adjusted_Net_Margin%",
};

export const modifyHeaders = (columnName: any) => {
  if (columns[columnName]) {
    return columns[columnName];
  } else return columnName;
};
